### ISSUE TITLE
Enter marker seems to be broken

### ISSUE THREAD

**Issue by schwim0341** [KlibrDM/esx_treasure#2]
Linux latest artifacts, up to date ES/ESX, install of the resource and starting with default options results in nothing happening when approaching the box.  No instruction to press input, Input(E) does nothing.

Any solution to this issue?

**Comment by KlibrDM** [comment]
Any errors? Make sure you also have all the items from the config file in the database and make sure you didn't already open the crates before (`treasure` table in the database).

**Comment by schwim0341** [comment]
Hi there again, Klibr and thanks for both the script and the response.  I managed to figure out the issue.  The script doesn't rebuild the crates on resource restart but only playerloaded so making changes and restarting the script wouldn't work.  I'd have to ask everyone to log out and back in to get the new crates.   I added the following below the player loaded to resolve my issue:

```
Citizen.CreateThread(function()
  while not tcChecked do
    Wait(0)
      PlayerData = xPlayer
      TriggerEvent('esx_treasure:checkcheck')
      tcChecked = true
  end
end)
```

**Comment by schwim0341** [comment]
Actually, that didn't seem to fix it like I thought it did.  It seems I have to ask everyone to leave the server for them to be able to interact with chests.

**Comment by KlibrDM** [comment]
So, from what I get, the problem occurs when you restart the script. I'm working on it.

**Comment by schwim0341** [comment]
You are a god among men.  Thanks so much for adding the fix.  The script is a much loved element of our server.
